# Generated by Django 3.1.7 on 2021-03-14 08:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mapsapiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 8, 33, 32, 667308, tzinfo=utc)),
        ),
    ]
